# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev/fast_sync_develop ]
  pull_request:
    branches: [ dev/fast_sync_develop ]

jobs:
  build:
    if: github.repository_owner == 'telosprotocol'
    runs-on: [self-hosted, Linux, X64]
    
    # for ci telos only
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build XTOP DEBUG
        run: |
          bash .github/scripts/fix_submodule.sh dev/fast_sync_develop
          bash .github/scripts/build_xtop.sh test